# CodeDeploy의 버전은 프로젝트의 버전이 아니므로 0.0 이외의 버전을 사용하면 에러 발생
version: 0.0
os: linux
files:
  - source: /     # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상 지정
    destination: /home/ec2-user/app/step2/zip/    # 이후 Jar 실행 등은 여기서 옮긴 파일들로 진행
    overwrite: yes    # 기존에 파일이 있으면 덮어쓸지 여부

# CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 수행
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포 단계에서 실행할 명령어를 지정
# ApplicationStart 단계에서 deploy.sh를 ec2-user 권한으로 실행
# 스크립트 실행 시간이 60초를 넘어가면 수행 실패 (무한정 기다릴 수는 없으므로 시간 제한 지정 필요)
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user